(load "~/quicklisp/setup.lisp")
(pushnew (truename "/Users/nikolaimatiushev/Projects/cl-workspace/") ql:*local-project-directories*)
(ql:quickload :cl-stack-calendars/tests)
(unless (rove:run :cl-stack-calendars/tests)
  (uiop:quit 1))
(uiop:quit 0)
