(defpackage #:cl-stack-calendars
  (:nicknames #:stack-calendars)
  (:use #:cl #:datetime-protocol)
  (:shadowing-import-from #:datetime-protocol
   #:+ #:- #:< #:<= #:> #:>= #:= #:/= #:min #:max)
  (:export
   ;; conditions
   #:calendar-error
   #:calendar-error-message
   #:calendar-not-found
   #:calendar-not-found-calendar-name
   #:invalid-holiday-rule
   #:session-boundary-error
   #:session-boundary-error-session
   #:session-boundary-error-date
   #:session-boundary-error-boundary

   ;; core protocol
   #:holiday-calendar
   #:business-day-p
   #:holiday-p
   #:holidays-between
   #:next-business-day
   #:previous-business-day
   #:add-business-days
   #:business-days-between
   #:adjust-date
   #:weekend-day-p
   #:calendar-weekend-days
   #:calendar-name
   #:calendar-as-of

   ;; holiday-observance value type
   #:holiday-observance
   #:holiday-observance-p
   #:make-holiday-observance
   #:holiday-observance-date
   #:holiday-observance-name

   ;; rule-calendar / DSL
   #:rule-calendar
   #:calendar-rules
   #:define-calendar
   #:make-fixed-holiday-rule
   #:make-nth-weekday-holiday-rule
   #:make-easter-holiday-rule
   #:make-computed-holiday-rule
   #:holiday-rule-authority
   #:holiday-rule-name
   #:holiday-rule-from
   #:holiday-rule-to

   ;; decree transfers / compensatory working days
   #:calendar-transfer
   #:make-calendar-transfer
   #:calendar-transfer-from
   #:calendar-transfer-to
   #:calendar-transfer-name
   #:calendar-transfer-authority
   #:calendar-working-day
   #:make-calendar-working-day
   #:calendar-working-day-date
   #:calendar-transfers
   #:calendar-working-days
   #:calendar-suppressed-dates
   #:make-extra-day-transfer

   ;; data-calendar
   #:data-calendar
   #:calendar-holidays-table
   #:make-data-calendar
   #:add-data-calendar-holiday
   #:load-data-calendar
   #:write-data-calendar-file

   ;; composite-calendar
   #:composite-calendar
   #:make-composite-calendar
   #:composite-calendar-calendars
   #:composite-calendar-mode

   ;; versioned-calendar
   #:versioned-calendar
   #:make-versioned-calendar
   #:versioned-calendar-snapshots
   #:calendar-snapshot
   #:make-calendar-snapshot
   #:snapshot-version-tag
   #:snapshot-recorded-at
   #:snapshot-calendar
   #:add-calendar-snapshot

   ;; trading / business hours
   #:trading-session
   #:trading-session-p
   #:make-trading-session
   #:trading-session-name
   #:trading-session-zone
   #:trading-session-open
   #:trading-session-close
   #:trading-session-overnight-p
   #:trading-session-labeled-by
   #:trading-session-calendar
   #:session-bounds
   #:session-open-p
   #:trading-day
   #:next-session-open
   #:session-duration

   ;; named registry
   #:register-calendar
   #:find-calendar
   #:unregister-calendar
   #:list-registered-calendars

   ;; starter calendars
   #:weekend-only-calendar
   #:target-calendar
   #:us-federal-holidays-calendar
   #:uk-bank-holidays-calendar
   #:load-gb-proclamations
   #:gb-proclamations
   #:gb-proclamation-for-year
   #:gb-transfers-for-year
   #:gb-suppressed-for-year
   #:ussr-holidays-calendar
   #:russian-holidays-calendar
   #:make-russian-holidays-calendar
   #:load-ru-transfer-decrees
   #:ru-transfer-decrees
   #:ru-decree-for-year
   #:ru-transfers-for-year
   #:ru-working-days-for-year
   #:japan-holidays-calendar
   #:china-holidays-calendar
   #:load-cn-transfer-notices
   #:cn-transfer-notices
   #:cn-notice-for-year
   #:cn-transfers-for-year
   #:cn-working-days-for-year
   #:india-holidays-calendar
   #:in-dopt-holidays
   #:in-dopt-for-year
   #:in-dopt-transfers-for-year
   #:germany-holidays-calendar
   #:france-holidays-calendar
   #:italy-holidays-calendar
   #:spain-holidays-calendar
   #:netherlands-holidays-calendar
   #:belgium-holidays-calendar
   #:austria-holidays-calendar
   #:poland-holidays-calendar
   #:sweden-holidays-calendar
   #:romania-holidays-calendar
   #:czechia-holidays-calendar
   #:greece-holidays-calendar
   #:portugal-holidays-calendar
   #:hungary-holidays-calendar
   #:bulgaria-holidays-calendar
   #:denmark-holidays-calendar
   #:finland-holidays-calendar
   #:slovakia-holidays-calendar
   #:ireland-holidays-calendar
   #:croatia-holidays-calendar
   #:lithuania-holidays-calendar
   #:slovenia-holidays-calendar
   #:latvia-holidays-calendar
   #:estonia-holidays-calendar
   #:cyprus-holidays-calendar
   #:luxembourg-holidays-calendar
   #:malta-holidays-calendar
   #:indonesia-holidays-calendar
   #:load-id-cuti-bersama
   #:id-cuti-bersama
   #:id-notice-for-year
   #:id-transfers-for-year
   #:bangladesh-holidays-calendar
   #:philippines-holidays-calendar
   #:ph-proclamations
   #:ph-notice-for-year
   #:ph-transfers-for-year
   #:vietnam-holidays-calendar
   #:thailand-holidays-calendar
   #:th-transfers
   #:th-notice-for-year
   #:th-transfers-for-year
   #:south-korea-holidays-calendar
   #:load-kr-temporary-holidays
   #:kr-temporary-holidays
   #:kr-notice-for-year
   #:kr-transfers-for-year
   #:myanmar-holidays-calendar
   #:malaysia-holidays-calendar
   #:my-transfers
   #:my-notice-for-year
   #:my-transfers-for-year
   #:taiwan-holidays-calendar
   #:north-korea-holidays-calendar
   #:nepal-holidays-calendar
   #:sri-lanka-holidays-calendar
   #:kazakhstan-holidays-calendar
   #:uzbekistan-holidays-calendar
   #:brazil-holidays-calendar
   #:mexico-holidays-calendar
   #:colombia-holidays-calendar
   #:co-emiliani-monday
   #:co-transfers
   #:co-notice-for-year
   #:co-transfers-for-year
   #:argentina-holidays-calendar
   #:canada-holidays-calendar
   #:peru-holidays-calendar
   #:australia-holidays-calendar
   #:venezuela-holidays-calendar
   #:chile-holidays-calendar
   #:cl-transfers
   #:cl-notice-for-year
   #:cl-transfers-for-year
   #:nigeria-holidays-calendar
   #:ethiopia-holidays-calendar
   #:dr-congo-holidays-calendar
   #:tanzania-holidays-calendar
   #:south-africa-holidays-calendar
   #:kenya-holidays-calendar
   #:uganda-holidays-calendar
   #:ghana-holidays-calendar
   #:pakistan-holidays-calendar
   #:egypt-holidays-calendar
   #:turkey-holidays-calendar
   #:iran-holidays-calendar
   #:saudi-arabia-holidays-calendar
   #:algeria-holidays-calendar
   #:morocco-holidays-calendar
   #:ukraine-holidays-calendar
   #:sudan-holidays-calendar
   #:iraq-holidays-calendar
   #:afghanistan-holidays-calendar
   #:angola-holidays-calendar
   #:mozambique-holidays-calendar
   #:madagascar-holidays-calendar
   #:cameroon-holidays-calendar
   #:cote-divoire-holidays-calendar
   #:niger-holidays-calendar
   #:burkina-faso-holidays-calendar
   #:mali-holidays-calendar
   #:malawi-holidays-calendar
   #:zambia-holidays-calendar
   #:yemen-holidays-calendar
   #:syria-holidays-calendar
   #:guatemala-holidays-calendar
   #:ecuador-holidays-calendar
   #:bolivia-holidays-calendar
   #:haiti-holidays-calendar
   #:cuba-holidays-calendar
   #:dominican-republic-holidays-calendar
   #:nicaragua-holidays-calendar
   #:el-salvador-holidays-calendar
   #:costa-rica-holidays-calendar
   #:panama-holidays-calendar
   #:uruguay-holidays-calendar
   #:new-zealand-holidays-calendar
   #:senegal-holidays-calendar
   #:chad-holidays-calendar
   #:somalia-holidays-calendar
   #:zimbabwe-holidays-calendar
   #:guinea-holidays-calendar
   #:rwanda-holidays-calendar
   #:benin-holidays-calendar
   #:togo-holidays-calendar
   #:sierra-leone-holidays-calendar
   #:south-sudan-holidays-calendar
   #:cambodia-holidays-calendar
   #:laos-holidays-calendar
   #:tajikistan-holidays-calendar
   #:papua-new-guinea-holidays-calendar
   #:hong-kong-holidays-calendar
   #:kyrgyzstan-holidays-calendar
   #:singapore-holidays-calendar
   #:switzerland-holidays-calendar
   #:norway-holidays-calendar
   #:belarus-holidays-calendar
   #:serbia-holidays-calendar
   #:georgia-holidays-calendar
   #:tunisia-holidays-calendar
   #:jordan-holidays-calendar
   #:united-arab-emirates-holidays-calendar
   #:azerbaijan-holidays-calendar
   #:libya-holidays-calendar
   #:lebanon-holidays-calendar
   #:oman-holidays-calendar
   #:kuwait-holidays-calendar
   #:israel-holidays-calendar
   #:population-order
   #:formation-years
   #:country-formation-year
   #:civil-research-from-year
   #:civil-from-year
   #:normative-coverage-by-population
   #:next-normative-gaps
   #:normative-calendar-codes
   #:calendar-earliest-from-year
   #:major-history-gaps

   ;; country / territory corpus (date-holidays)
   #:country-holiday-calendar
   #:country-calendar
   #:load-country-calendar
   #:list-country-calendars
   #:country-calendar-codes
   #:country-calendar-code
   #:country-calendar-source
   #:country-calendar-license
   #:country-calendar-note
   #:country-calendar-year-range
   #:clear-country-calendar-cache))

(in-package #:cl-stack-calendars)
